AWSTemplateFormatVersion: 2010-09-09

Description: Cloudformation template for 'Troubleshooting Logging with CloudTrail and S3' learning activity


Resources:

  #
  # CloudTrail
  #
  CloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      IncludeGlobalServiceEvents: true
      IsLogging: false
      IsMultiRegionTrail: false
      S3BucketName: !Ref CloudTrailBucket
      CloudWatchLogsLogGroupArn: !GetAtt CloudTrailLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CloudTrailRole.Arn
      EventSelectors:
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Sub "${S3BucketWithObjectLoggingOn.Arn}/*"
          IncludeManagementEvents: true
          ReadWriteType: All  
    DependsOn:
      # Wait for the S3 bucket policy to be created, which implies 
      # that the bucket itself has been created
      - CloudTrailBucketPolicy

  CloudTrailRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 
              - sts:AssumeRole
            Effect: Allow
            Principal: 
              Service: 
                - cloudtrail.amazonaws.com
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - logs:*
                Resource: "*"

  #
  # CloudWatch
  #
  CloudTrailLogGroup:
    Type: AWS::Logs::LogGroup

  #
  # S3
  #
  S3BucketWithObjectLoggingOn:
    Type: AWS::S3::Bucket

  S3Bucket2:
    Type: AWS::S3::Bucket

  CloudTrailBucket:
    Type: AWS::S3::Bucket

  CloudTrailBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CloudTrailBucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal: { Service: cloudtrail.amazonaws.com }
            Action: s3:GetBucketAcl
            Resource: !GetAtt CloudTrailBucket.Arn
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal: { Service: cloudtrail.amazonaws.com }
            Action: s3:PutObject
            Resource: !Sub "${CloudTrailBucket.Arn}/*" 
            Condition: # ensure we have control of objects written to the bucket
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"
